services:
  - type: web
    name: car-rental-backend
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: car-rental-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: CHAPA_MODE
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: CHAPA_CALLBACK_URL
        sync: false
      - key: CHAPA_RETURN_URL
        sync: false
      - key: CHAPA_WEBHOOK_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false

databases:
  - name: car-rental-db
    plan: free
    databaseName: car_rental
